# Generated by Django 5.1.4 on 2025-01-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_admin_bulk_io", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkioexport",
            name="file",
            field=models.FileField(max_length=1024, upload_to=""),
        ),
        migrations.AlterField(
            model_name="bulkioimport",
            name="file",
            field=models.FileField(max_length=1024, upload_to=""),
        ),
    ]
