# Generated by Django 5.1.4 on 2025-01-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "django_admin_bulk_io",
            "0002_alter_bulkioexport_file_alter_bulkioimport_file",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkioexport",
            name="title",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bulkioimport",
            name="title",
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
    ]
