# Generated by Django 5.1.4 on 2025-01-21 07:28

import django_admin_bulk_io.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_admin_bulk_io", "0003_bulkioexport_title_bulkioimport_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulkioexport",
            name="title",
        ),
        migrations.RemoveField(
            model_name="bulkioimport",
            name="title",
        ),
        migrations.AlterField(
            model_name="bulkioexport",
            name="file",
            field=models.FileField(
                max_length=1024, upload_to=django_admin_bulk_io.models._upload_to
            ),
        ),
        migrations.AlterField(
            model_name="bulkioimport",
            name="file",
            field=models.FileField(
                max_length=1024, upload_to=django_admin_bulk_io.models._upload_to
            ),
        ),
    ]
