# Generated by Django 5.1.1 on 2025-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_io_test", "0002_like_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created",
            field=models.DateField(),
        ),
    ]
