# Generated by Django 5.1.4 on 2025-01-23 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulk_io_test", "0003_alter_comment_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bulk_io_test.comment",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(to="bulk_io_test.like"),
        ),
    ]
