# Generated by Django 5.1.4 on 2025-01-23 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_io_test", "0004_post_comment_post_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
