# Generated by Django 5.1.1 on 2025-01-24 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_io_test", "0005_alter_post_likes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Like",
        ),
    ]
